export const AreaVarietys = [
  "Acitana",
  "Afrocheiro",
  "Aglianco",
  "Alicante Boushet",
  "Albarino",
  "Airen",
  "Ancelotta",
  "Alvarinho",
  "Aligoté",
  "Antão Vaz",
  "Ansonica",
  "Aragonez",
  "Arbane",
  "Aramon",
  "Arneis",
  "Arinto",
  "Arinarnoa",
  "Avesso",
  "Azal",
  "Baccus",
  "Baco Noir",
  "Baga",
  "Bastardo",
  "Barbera",
  "Bianchetta",
  "Bobal",
  "Bical",
  "Blaufränkisch",
  "Bonarda",
  "Bordô",
  "Bourboulenc",
  "Borraçal",
  "Brunello",
  "Brachetto",
  "Cabernet Franc",
  "Cabernet Sauvignon",
  "Calabrese",
  "Carignan",
  "Camarate",
  "Canaiolo",
  "Carmine",
  "Cariñena",
  "Carménère",
  "Casavecchia",
  "Catarrato",
  "Catawba",
  "Castelão",
  "Cerceal",
  "Chambourcin",
  "Chancellor",
  "Chardonnay",
  "Charbono",
  "Chasselas",
  "Chenin Blanc",
  "Ciliegiolo",
  "Cinsault",
  "Clairette",
  "Cococciola",
  "Códega",
  "Códega do Larinho",
  "Colombard",
  "Colorino",
  "Cortese",
  "Concord(Francesa)",
  "Corvinone",
  "Corvina Veronese",
  "Corvina",
  "Criolla Chica",
  "Cournoise",
  "Counoise",
  "Dolce Noir",
  "Dolcetto",
  "Donzelinho",
  "Drupeggio",
  "Dutchess",
  "Dornfelder",
  "Encruzado",
  "Espadeiro",
  "Falanghina",
  "Fernão Pires",
  "Fiano",
  "Fiano di Avellino",
  "Furmint",
  "Flora",
  "Galatena",
  "Gamay",
  "Garciano",
  "Garganega",
  "Garnacha Branca",
  "Garnacha",
  "Garnacha Negra",
  "Glera(Prosecco)",
  "Gewürztraminer",
  "Gouveio",
  "Graciano",
  "Grechetto",
  "Greco di Tufo",
  "Grenache - Garnacha",
  "Grenache",
  "Grenache Blanc",
  "Gros Verdot",
  "Grenache Noir",
  "Grolleau",
  "Grüner Veltliner",
  "Herbemont",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];
