export const DrivingSystems = [
  'Latada',
  'Espaldeira',
  'Carrosel',
  'Estaqueado',
  'Extensiva',
  'Intensiva',
  'Líder central',
  'Líder central em Espiral',
  'Líder central em Muro Frutal',
  'Líder central em X',
  'Em T',
  'Em Y',
  'Lira',
  'Manjedoura',
  'Multilíder',
  'Peão Central',
  'Rasteiro',
  'Sem Condução',
  'Semi intensiva',
  'Taça',
  'Tutorado fitilho',
  'Uso de pneus',
  'Vaso',
  'Vaso Policônico',
];
